title: Peter Guntrip - CV
fullName: Peter Guntrip
phoneNumber: 0773 059 4343
email: peter@guntrisoft.com
twitterHandle: "@guntrisoft"
twitterURL: "http://www.twitter.com/guntrisoft"
linkedInURL: "http://uk.linkedin.com/in/pguntrip"
linkedInLinkText: "pguntrip"
